Update UDP client connection syntax to use udpin://
dronecore/docs pull request #288
Opened 2024-08-19 15:45 UTC by KarthiAru

Changed all instances of the deprecated UDP connection syntax udp://:PORT to the recommended udpin://:PORT following the deprecation warning: Connection using udp:// is deprecated, please use udpin:// or udpout:// (cli_arg.cpp:28)

2024-08-20 01:30 UTC, julianoes requested changes
And it should be `udpin://0.0.0.0:14540` with the new syntax.

Note that I won't merge this just yet until the release is out with the changes.

2024-08-20 03:50 UTC, KarthiAru commented
Done. Updated to include 0.0.0.0

2024-08-20 21:38 UTC, julianoes approved these changes

2025-03-16 18:06 UTC, julianoes commented
Sorry, I missed to merge this before moving the docs over to https://github.com/mavlink/MAVSDK/tree/main/docs. I have since done a pass, and hopefully fixed most of these.

2025-03-16 18:06 UTC, closed without merging